fix: maximum updates Portal.tsx (#29)
* Update Portal.tsx

Fix for the following error:
error-boundary-callbacks.ts:80 Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at getRootForUpdatedFiber (react-dom-client.development.js:3860:11)
    at enqueueConcurrentHookUpdate (react-dom-client.development.js:3820:14)
    at dispatchSetStateInternal (react-dom-client.development.js:8121:18)
    at dispatchSetState (react-dom-client.development.js:8081:7)
    at Portal.useEffect (Portal.js:63:5)

* Update Portal.tsx

Missed dependency

* Update Portal.tsx

If getContainer is a stable useCallback(() => myRef.current), the effect won't re-run when myRef.current changes because the function reference stays the same.

* chore: adjust

---------

Co-authored-by: 二货机器人 <smith3816@gmail.com>